import { PropsWithChildren } from "react";

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html>
      <head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
    </html>
  );
}
