import "../styles/globals.css";
import type { PropsWithChildren } from "react";
import AuthProvider from "../context/auth-context";
import { ClientProvider } from "../context/trpc-context";
import { TopNav } from "../components/layout/TopNav";
import { FooterContent } from "../components/layout/FooterContent";

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html>
      <head>
        <title>fragile-flower</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex min-h-screen flex-col">
        <AuthProvider>
          <ClientProvider>
            <header className="sticky w-full py-4">
              <TopNav />
            </header>

            <main className="mx-auto w-full max-w-7xl flex-grow overflow-y-scroll">
              {props.children}
            </main>

            <footer className="mx-auto mb-0 w-full bg-[#29314D] py-4">
              <FooterContent />
            </footer>
          </ClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
