import "../styles/globals.css";
import type { PropsWithChildren } from "react";
import SupabaseProvider from "../context/AuthContext";
import { createServerClient } from "../lib/supabase/supabase";

export default async function RootLayout(props: PropsWithChildren) {
  const supabase = createServerClient();
  const { data } = await supabase.auth.getSession();

  return (
    <html>
      <head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SupabaseProvider session={data.session}>
          {props.children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
