import "../styles/globals.css";
import type { PropsWithChildren } from "react";
import AuthProvider from "../context/auth-context";
import { ClientProvider } from "../context/trpc-context";

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html>
      <head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <AuthProvider>
          <ClientProvider>{props.children}</ClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
